title: "Hi, I\’m Skylar Gagnon — Computer Engineer & Security Researcher"
description: "Senior Honors student at UNH | Microarchitectural Security | Machine Learning Enthusiast"
downloads: true
theme: jekyll-theme-minimal

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
