title: 'AutoMAD: Leveraging Large Language Models for Automated Microarchitectural Attack Discovery'
theme: jekyll-theme-minimal
# description: Senior project website
# downloads: true

# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
